name: rppg_training
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12.3
  - pytorch=2.1.0
  - torchvision=0.16.0
  - pytorch-cuda=12.1
  - numpy=1.26
  - scipy=1.11
  - pyyaml=6.0
  - tqdm=4.66
  - pip
  - pip:
    - opencv-python>=4.8.0
    - tensorboard>=2.15.0
    - gdown>=4.7.0
